#!/usr/bin/env sh

# Простая проверка длины сообщения коммита
commit_regex='^.{1,50}$'

error_msg="Сообщение коммита должно быть от 1 до 50 символов"

if ! grep -qE "$commit_regex" "$1"; then
    echo "Неверный формат коммита!" >&2
    echo "$error_msg" >&2
    echo "Ваше сообщение: $(cat $1)" >&2
    exit 1
fi 